# Generated by Django 4.2.4 on 2023-08-29 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_type", models.CharField(max_length=50)),
                ("car_name", models.CharField(max_length=20)),
                ("slug", models.SlugField(max_length=20)),
                ("description", models.TextField(max_length=500)),
                ("car_year", models.IntegerField()),
                (
                    "car_image",
                    models.ImageField(blank=True, upload_to="photo/carcategories"),
                ),
            ],
            options={
                "verbose_name": "carcategory",
                "verbose_name_plural": "carcategories",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=50)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("product_model", models.CharField(max_length=50)),
                ("product_year", models.CharField(max_length=50)),
                ("product_sit", models.CharField(max_length=50)),
                ("product_transmission", models.CharField(max_length=50)),
                ("product_doors", models.CharField(max_length=50)),
                ("product_price_day", models.IntegerField(default=0)),
                ("product_price_week", models.IntegerField(default=0)),
                ("product_price_month", models.IntegerField(default=0)),
                (
                    "product_images",
                    models.ImageField(blank=True, upload_to="photo/products"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car_rentals_page.carcategories",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
    ]
