# Generated by Django 4.2.4 on 2023-09-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Country',
            new_name='country',
        ),
    ]
