# Generated by Django 4.2.4 on 2023-08-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_location", models.CharField(max_length=50)),
                ("d_location", models.CharField(max_length=50)),
                ("p_date", models.DateTimeField()),
                ("d_date", models.DateTimeField()),
                ("p_up_time", models.TextField()),
            ],
        ),
    ]
