# Generated by Django 4.2.4 on 2023-08-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookings",
            options={"verbose_name": "bookings", "verbose_name_plural": "bookings"},
        ),
        migrations.AlterField(
            model_name="bookings",
            name="d_date",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="p_date",
            field=models.TextField(),
        ),
    ]
